### ISSUE TITLE
З А Ч Е М? 

### ISSUE THREAD

**Issue by Seminioni** [gearmobile/eventida#1]
Ты прикрутил ради одного дропдауна жирнейший select2? Зачем тебе это?

**Comment by gearmobile** [comment]
упс! )) а что посоветуешь - полегче? )

**Comment by Seminioni** [comment]
Ради одного, думаю, можно и свой вариант написать. Или с codepen что-нибудь взять. Всяко будет интереснее повозиться самому над этим. имхо конечно же

**Comment by gearmobile** [comment]
нет, в данном случае верстка делалась по принципу - "быстро и надежно". "быстро" - это есть готовое решение. "надежно" - плагин проверенный на работоспособность.
искать на codepen решение, проверять его на работоспособность - это сколько же времени нужно?
